# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x2tOJWfz-bhaPTu-xQpejaZPaG73yHOe
"""

import streamlit as st
import joblib
import numpy as np
import pymongo
from datetime import datetime

# 1. LOAD THE MODEL
# This assumes the .pkl file is in the same GitHub folder
model = joblib.load('phishing_detector (1).pkl')
# 2. DATABASE LOGGING FUNCTION
# This will use the "Secrets" you set in the Streamlit Dashboard
MONGO_URI = st.secrets["mongo_uri"]

def log_to_cloud(url, verdict):
    try:
        client = pymongo.MongoClient(MONGO_URI, serverSelectionTimeoutMS=5000)
        db = client["phishing_db"]
        collection = db["live_logs"]
        collection.insert_one({
            "url": url,
            "prediction": verdict,
            "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        })
    except:
        pass # App keeps running even if DB connection blinks

# 3. YOUR UI CODE (THE SNIPPET YOU SHARED)
st.set_page_config(page_title="Phishing Shield AI", page_icon="🛡️")
st.title("🛡️ Phishing Website Detector")

st.subheader("🔍 Scan a URL")
url_input = st.text_input("Paste the website link here:", placeholder="https://www.example.com")

st.markdown("---")
st.write("### 📊 Structural Analysis")
st.info("Based on your dataset, we analyze these key indicators:")

col1, col2 = st.columns(2)
with col1:
    ssl = st.selectbox("Does it have a valid SSL/HTTPS?", [1, 0, -1], help="1=Trusted, 0=Non-trusted, -1=No SSL")
    anchor = st.selectbox("URL Anchor Percentage", [1, 0, -1], help="Percentage of links pointing to other domains")

with col2:
    traffic = st.selectbox("Web Traffic Rank", [1, 0, -1], help="1=High/Safe, 0=Medium, -1=Low/Unknown")
    prefix = st.selectbox("Does URL have '-' in Domain?", [1, -1], help="1=No (Safe), -1=Yes (Suspicious)")

if st.button("🚀 Analyze Security"):
    if url_input == "":
        st.warning("Please enter a URL first!")
    else:
        feature_count = model.n_features_in_
        feature_list = [0.0] * feature_count 
        feature_list[7] = float(ssl)
        feature_list[13] = float(anchor)
        feature_list[25] = float(traffic)
        feature_list[1] = float(prefix)

# Convert to NumPy array and force the 2D shape (1 row, 30 columns)
# This is the "Gold Standard" way to prevent TypeErrors in Scikit-Learn
        features_as_array = np.array(feature_list, dtype=np.float64).reshape(1, -1)

# Run the prediction
        prediction = model.predict(features_as_array)
        # 4. THE RESULT & LOGGING
        if prediction[0] == 1:
            result = "LEGITIMATE"
            st.success(f"✅ **{result}**: {url_input} appears safe.")
        else:
            result = "PHISHING"
            st.error(f"🚨 **{result}**: {url_input} is suspicious!")

        # Call the MongoDB function
        log_to_cloud(url_input, result)
        st.toast("Result logged to MongoDB Atlas Cloud")

st.sidebar.info("Final Project | BCA | Accuracy: 96.7%")
